name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rubocop:
    name: runner / rspec
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1.110.0
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: rspec tests
        run: script/test -d
